import os.path
import salt.utils

config_tpl = '''
# Generated by Salt, do not edit!
server {
  listen 80;
  server_name %s;

%s
}
'''

# TODO: Add TLS support
def present(name, conf):
  '''
  Ensure an nginx site is present and enabled.

  name
    Name of the site

  conf
    Config file, in case you need more fine-grained control over the configuration.
    Will be included as part of the server block.
  '''
  # Workaround for __states__ not being defined in older versions of Salt
  try:
    __states__
  except NameError:
    __states__ = salt.loader.states(__opts__, __salt__)

  ret = {
    'name': name,
    'result': None,
    'comment': '',
    'changes': { }
  }

  filename = '/etc/nginx/sites-available/' + name
  linkname = '/etc/nginx/sites-enabled/' + name

  additional_config_bits = __salt__['cp.get_file_str'](conf, saltenv=__env__)
  config = config_tpl % (name, additional_config_bits)

  current_config = ''
  if os.path.exists(filename):
    with salt.utils.fopen(filename) as config_file:
      current_config = config_file.read()

  if config == current_config.strip():
    res = __states__['file.symlink'](name=linkname, target=filename)
    if res['result'] == False:
      ret['result'] = False
      ret['comment'] = 'Failed to enable site config.'
      return ret

    ret['result'] = True
    ret['comment'] = 'Site is up to date.'
  elif __opts__['test']:
    ret['comment'] = 'Site will be updated.'
    ret['changes'] = {
      'old': current_config,
      'new': config
    }
    return ret

  try:
    with salt.utils.fopen(filename, 'w') as config_file:
      config_file.write(config)

    res = __states__['file.symlink'](name=linkname, target=filename)
    if res['result'] == False:
      ret['result'] = False
      ret['comment'] = 'Failed to enable site config.'
      return ret

    ret['result'] = True
    ret['comment'] = 'Successfully wrote site config.'
    ret['changes'] = {
      'old': current_config,
      'new': config
    }
  except IOError:
    ret['result'] = False
    ret['comment'] = 'Failed to write site config.'

  return ret
